"""Add shared_links table

Revision ID: 8eee981d5618
Revises: c3b4482ab43d
Create Date: 2025-04-29 08:24:10.504847

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8eee981d5618'
down_revision = 'c3b4482ab43d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shared_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('share_token', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('privacy_level', sa.String(length=20), nullable=False),
    sa.Column('modules', sa.Text(), nullable=False),
    sa.Column('date_range_start', sa.DateTime(), nullable=False),
    sa.Column('date_range_end', sa.DateTime(), nullable=False),
    sa.Column('template_type', sa.String(length=20), nullable=False),
    sa.Column('personal_message', sa.String(length=255), nullable=True),
    sa.Column('theme', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('shared_links', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shared_links_share_token'), ['share_token'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shared_links', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shared_links_share_token'))

    op.drop_table('shared_links')
    # ### end Alembic commands ###
