"""Add user privacy settings

Revision ID: b720b8fdd596
Revises: 8eee981d5618
Create Date: 2025-04-29 08:24:57.661793

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b720b8fdd596'
down_revision = '8eee981d5618'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('default_share_privacy', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('default_share_modules', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('default_share_template', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('default_share_expiry', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('default_share_expiry')
        batch_op.drop_column('default_share_template')
        batch_op.drop_column('default_share_modules')
        batch_op.drop_column('default_share_privacy')

    # ### end Alembic commands ###
